/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.VehiculoController;
import java.util.*;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Model.*;

/**
 *
 * @author marco
 */
public class ListarForm extends javax.swing.JFrame {
    
    private VehiculoController vehiculoController;
    private JTable table;
    private JScrollPane scrollPane;
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarForm.class.getName());

    /**
     * Creates new form ListarForm
     */
    public ListarForm(VehiculoController vehiculoController) {
        initComponents();
        this.vehiculoController = vehiculoController;
        List<Vehiculo> vehiculos = vehiculoController.getVehiculoFromDB();
        String[] columNames = {"Marca","Modelo","Patente","Precio","Cantidad de Puertas"};
        Object[][] data = new Object[vehiculos.size()][columNames.length];
        
        for(int i = 0; i<vehiculos.size(); i++){
            Vehiculo v = vehiculos.get(i);
            data[i][0] = v.getMarca();
            data[i][1] = v.getModelo();
            data[i][2] = v.getPatente();
            data[i][3] = v.getPrecio();
            data[i][4] = ((Auto) v).getCanPuertas();
        }
        DefaultTableModel model = new DefaultTableModel(data,columNames);
        jTable1.setModel(model);
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
